// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QAwebApp.Models;

namespace QAwebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190404073205_Email")]
    partial class Email
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QAwebApp.Models.FormModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AssessmentPeriod")
                        .HasColumnType("datetime");

                    b.Property<string>("BCMGrComment");

                    b.Property<int>("BCMScore");

                    b.Property<string>("BCMUnitComment");

                    b.Property<string>("Bul1");

                    b.Property<string>("Bul2");

                    b.Property<string>("Bul3");

                    b.Property<string>("Country");

                    b.Property<DateTime?>("DateOfAssessment")
                        .HasColumnType("datetime");

                    b.Property<string>("Division");

                    b.Property<string>("EmailSent");

                    b.Property<string>("ICCGrComment");

                    b.Property<int>("ICCScore");

                    b.Property<string>("ICCUnitComment");

                    b.Property<string>("IRHGrComment");

                    b.Property<int>("IRHScore");

                    b.Property<string>("IRHUnitComment");

                    b.Property<string>("KRIGrComment");

                    b.Property<int>("KRIScore");

                    b.Property<string>("KRIUnitComment");

                    b.Property<string>("ManagerSid");

                    b.Property<string>("NPAPGrComment");

                    b.Property<string>("NPAPScore");

                    b.Property<string>("NPAPUnitComment");

                    b.Property<string>("ORSARTSAGrComment");

                    b.Property<string>("ORSARTSAScore");

                    b.Property<string>("ORSARTSAUnitComment");

                    b.Property<string>("UnitAssessor");

                    b.Property<int?>("UnitResponsibleId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UnitResponsibleId");

                    b.HasIndex("UserId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("QAwebApp.Models.UnitResponsibleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Sid");

                    b.HasKey("Id");

                    b.ToTable("UnitResponsibleModel");
                });

            modelBuilder.Entity("QAwebApp.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Sid");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QAwebApp.Models.FormModel", b =>
                {
                    b.HasOne("QAwebApp.Models.UnitResponsibleModel", "UnitResponsible")
                        .WithMany()
                        .HasForeignKey("UnitResponsibleId");

                    b.HasOne("QAwebApp.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
